package com.devahoy.learn30androidlibraries;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.devahoy.learn30androidlibraries.Player;

import com.devahoy.learn30androidlibraries.PlayerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playerDaoConfig;

    private final PlayerDao playerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playerDaoConfig = daoConfigMap.get(PlayerDao.class).clone();
        playerDaoConfig.initIdentityScope(type);

        playerDao = new PlayerDao(playerDaoConfig, this);

        registerDao(Player.class, playerDao);
    }
    
    public void clear() {
        playerDaoConfig.getIdentityScope().clear();
    }

    public PlayerDao getPlayerDao() {
        return playerDao;
    }

}
