package com.devahoy.learn30androidlibraries;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAYER.
 */
public class Player {

    private Long id;
    private String name;
    private String club;

    public Player() {
    }

    public Player(Long id) {
        this.id = id;
    }

    public Player(Long id, String name, String club) {
        this.id = id;
        this.name = name;
        this.club = club;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClub() {
        return club;
    }

    public void setClub(String club) {
        this.club = club;
    }

}
